//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReservation
    {
        public int IDReservation { get; set; }
        public int IDBook { get; set; }
        public string Reader { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Employee { get; set; }
        public string Status { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual StatusBook StatusBook { get; set; }
    }
}
